u

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,3 +1,14 @@
 #!/bin/bash
-echo $PYCODE > code.py
-python3 code.py
+
+# Get the Python code from the environment variable
+python_code="$PYCODE"
+
+# Check if the environment variable is set
+if [ -z "$python_code" ]; then
+    echo "Error: Environment variable not set."
+    exit 1
+fi
+
+# Run the Python code
+python3 -c "$python_code"
+
